apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi